version: '2.4'

services:

  database_pub:
    image: postgres:12
    container_name: database_pub
    ports:
      - 5409:5432
    environment:
      POSTGRESS_PASSWORD: pas123
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  database_sub:
    image: postgres:12
    container_name: database_sub
    ports:
      - 5406:5432
    environment:
      POSTGRESS_PASSWORD: pas123
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  publisher:
      image: publisher:1
      ports:
        - 8089:8089
      restart: always
      links:
        - database_pub


  subscriber:
      image: subscriber:1
      ports:
        - 8086:8086
      restart: always
      links:
        - database_sub






